
  db:
      image: mongo:latest
      ports:
        - 27017:27017
  mongo-seed:
      build: ./mongo-seed
      links:
        - db
  web:
    build: .
    command: python -u app.py
    ports:
      - "80:80"
    volumes:
      - .:/todo
    links:
      - db